<a href="https://colab.research.google.com/github/rinshan-bot/natutal-language-processing/blob/main/nueral_network_in_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import sys

In [17]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0
print(x_train.shape)

(60000, 784)


In [20]:
model = keras.Sequential(
    [
        layers.Input(shape=(28*28)), # This layer here will helps to print summary of model before fit
        layers.Dense(512,activation='relu'),
        layers.Dense(256,activation='relu'),
        layers.Dense(10), # 10 Outputs
    ]
)
print(model.summary())
# sys.exit()
# model = keras.Sequential()
# model.add(keras.Input(shape=(784)))
# model.add(layers.Dense(512, activation="relu"))
# model.add(layers.Dense(256, activation="relu", name="my_layer"))
# model.add(layers.Dense(10))
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 512)               401920    
                                                                 
 dense_21 (Dense)            (None, 256)               131328    
                                                                 
 dense_22 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 - 5s - loss: 0.1869 - accuracy: 0.9439 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.0790 - accuracy: 0.9750 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 4s - loss: 0.0561 - accuracy: 0.9827 - 4s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 4s - loss: 0.0415 - accuracy: 0.9870 - 4s/

[0.09114302694797516, 0.9750000238418579]

In [21]:
# Different method
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)
model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_23 (Dense)            (None, 512)               401920    
                                                                 
 dense_24 (Dense)            (None, 256)               131328    
                                                                 
 dense_25 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 - 5s - loss: 0.1855 - accuracy: 0.9436 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 5s - loss: 0.0800 - accuracy: 0.9753 - 5s/epoch - 3ms/step
Epoch 3/5
1875/1875 - 4s - loss: 0.0544 - accuracy: 0.9826 - 4s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 4s - loss: 0.0403 - accuracy: 0.9864 - 4s/

[0.06469424068927765, 0.9815000295639038]

In [22]:
# Keras Functional API
inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x = layers.Dense(256, activation="relu", name="second_layer")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),# Activation softmax given in the output layer, so from_logits = False
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 5s - loss: 0.1846 - accuracy: 0.9432 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.0790 - accuracy: 0.9753 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 5s - loss: 0.0541 - accuracy: 0.9825 - 5s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 5s - loss: 0.0408 - accuracy: 0.9866 - 5s/epoch - 3ms/step
Epoch 5/5
1875/1875 - 5s - loss: 0.0336 - accuracy: 0.9886 - 5s/epoch - 3ms/step
313/313 - 1s - loss: 0.0684 - accuracy: 0.9802 - 957ms/epoch - 3ms/step


[0.0683709979057312, 0.9801999926567078]

In [23]:
print(model.summary()) # Name is given in each layer

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 784)]             0         
                                                                 
 first_layer (Dense)         (None, 512)               401920    
                                                                 
 second_layer (Dense)        (None, 256)               131328    
                                                                 
 dense_26 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
# Different method
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))
model = keras.Model(inputs=model.inputs,outputs=[model.layers[-2].output]) # check here

features = model.predict(x_train)
print(features)
print(features.shape)

# model.compile(
#     loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
#     optimizer=keras.optimizers.Adam(learning_rate=0.001),
#     metrics=["accuracy"],
# )
# model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)
# model.evaluate(x_test,y_test,batch_size=32,verbose=2)

1875/1875 [==============================] - 3s 1ms/step
[[0.         0.         0.11914954 ... 0.         0.05840763 0.16553107]
 [0.         0.         0.16789174 ... 0.         0.21142668 0.23205473]
 [0.         0.         0.         ... 0.07483047 0.01181898 0.26795885]
 ...
 [0.         0.         0.4474729  ... 0.         0.01816628 0.12823659]
 [0.15860078 0.03627227 0.25473797 ... 0.         0.55655503 0.19232082]
 [0.         0.08942214 0.27481958 ... 0.         0.31744528 0.06734636]]
(60000, 256)


In [28]:
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))
model = keras.Model(inputs=model.inputs,outputs=[model.get_layer('my_layer').output]) # check here

features = model.predict(x_train)
print(features)
print(features.shape)

1875/1875 [==============================] - 3s 2ms/step
[[0.09737147 0.05309635 0.         ... 0.0411184  0.30399966 0.        ]
 [0.29978648 0.10383243 0.         ... 0.01943773 0.         0.        ]
 [0.09891142 0.34768146 0.         ... 0.         0.         0.        ]
 ...
 [0.15921034 0.         0.         ... 0.         0.21316943 0.        ]
 [0.0360838  0.03637378 0.         ... 0.         0.         0.        ]
 [0.23892187 0.16737075 0.16492969 ... 0.         0.         0.        ]]
(60000, 256)


In [30]:
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))
model = keras.Model(inputs=model.inputs,outputs=[layer.output for layer in model.layers]) # check here

features = model.predict(x_train)
for f in features:
  print(f)
  print(f.shape)

1875/1875 [==============================] - 3s 2ms/step
[[0.17570661 0.3976204  0.         ... 0.         0.18548906 0.1453084 ]
 [0.         0.41661283 0.00104303 ... 0.         0.5052164  0.        ]
 [0.         0.2652535  0.         ... 0.04241446 0.62434196 0.        ]
 ...
 [0.         0.3068961  0.         ... 0.         0.26389614 0.        ]
 [0.         0.         0.         ... 0.32299846 0.3897093  0.        ]
 [0.         0.06962249 0.         ... 0.04564432 0.23506513 0.        ]]
(60000, 512)
[[0.0236685  0.         0.25300035 ... 0.46266305 0.22347276 0.        ]
 [0.5201557  0.         0.6905123  ... 0.         0.12561728 0.24993773]
 [0.1375761  0.         0.19560988 ... 0.49264723 0.47374552 0.24993253]
 ...
 [0.09924483 0.         0.05338606 ... 0.4322732  0.30810225 0.14675204]
 [0.23833588 0.         0.40938798 ... 0.03649402 0.16046292 0.25714156]
 [0.17953762 0.         0.         ... 0.         0.31693277 0.19330464]]
(60000, 256)
[[-0.3603517  -0.4377178  -0.