<a href="https://colab.research.google.com/github/rinshan-bot/natutal-language-processing/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
# To avoid the GPU Warning message
import tensorflow as tf
# physical_devices = tf.config.list_physical_devices('GPU')
# print(physical_devices)
# tf.config.experimental.set_memory_growth(physical_devices[0],True)

Tensor if multidiamensional array



1. Initialization  of tensors
2. Mathematical operations
3. Indexing
4. Reshaping

### Initialization  of tensors

In [16]:
x = tf.constant(4)
print(x)
x = tf.constant(4.0)
print(x)
x = tf.constant(4.0,shape=(1,1))
print(x)
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)
x = tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [19]:
x = tf.ones((3,3))
print(x)
x = tf.zeros((3,3))
print(x)
x = tf.eye(3) # Indentity matrix
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [31]:
x = tf.random.normal((3,3),mean=0,stddev=1)
print(x)
x = tf.random.uniform((1,3),minval=1,maxval=2)
print(x)

tf.Tensor(
[[-0.00839665  0.12513153 -1.0209956 ]
 [ 0.28299028 -1.8376423   1.1970675 ]
 [-0.4849051   0.39539403 -1.1354313 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[1.2976923 1.9628847 1.4288737]], shape=(1, 3), dtype=float32)


In [35]:
x = tf.range(9)
print(x)
x = tf.range(start=2,limit=10,delta=2) # Delta is step
print(x)
y = tf.cast(x,dtype=tf.float64)
print(y)
#tf.float,tf.int,tf.int for other types of casting

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tf.Tensor([2. 4. 6. 8.], shape=(4,), dtype=float64)


### Mathematical operations

In [39]:
x = tf.constant([4,5,6])
y = tf.constant([7,8,9])
z = tf.add(x,y) # OR
z = x+y
print(z)
z = tf.subtract(x,y) # OR
z = x - y
print(z)
z = tf.divide(x,y) # OR
z = x / y
print(z)
z = tf.multiply(x,y) # OR
z = x * y
print(z)

tf.Tensor([11 13 15], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.57142857 0.625      0.66666667], shape=(3,), dtype=float64)
tf.Tensor([28 40 54], shape=(3,), dtype=int32)


In [43]:
# Dot product
z = tf.tensordot(x,y,axes=1)
print(z)
# Manually do the dot product
z = tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(122, shape=(), dtype=int32)
tf.Tensor(122, shape=(), dtype=int32)


In [52]:
# Matrix multiplication
x = tf.random.normal((3,4))
y = tf.random.normal((4,3))
z = tf.matmul(x,y)
print(z) # OR
z = x @ y
print(z)

tf.Tensor(
[[-0.34163722  0.72761685 -3.102731  ]
 [-0.6558639   1.7815247  -0.19629979]
 [-0.60043573  0.02936329  1.5036434 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.34163722  0.72761685 -3.102731  ]
 [-0.6558639   1.7815247  -0.19629979]
 [-0.60043573  0.02936329  1.5036434 ]], shape=(3, 3), dtype=float32)


### Indexing

In [14]:
x = tf.constant([7,1,45,15,4,5,67,8,10])
print(x[:])
print(x[2:])
print(x[2:5])
print(x[::2])
print(x[::-1])

tf.Tensor([ 7  1 45 15  4  5 67  8 10], shape=(9,), dtype=int32)
tf.Tensor([45 15  4  5 67  8 10], shape=(7,), dtype=int32)
tf.Tensor([45 15  4], shape=(3,), dtype=int32)
tf.Tensor([ 7 45  4 67 10], shape=(5,), dtype=int32)
tf.Tensor([10  8 67  5  4 15 45  1  7], shape=(9,), dtype=int32)


In [15]:
# Get index of tensor
indices = tf.constant([0,3,4])
x_indices = tf.gather(x,indices)
print(x_indices)

tf.Tensor([ 7 15  4], shape=(3,), dtype=int32)


In [18]:
# Indexing of matrix
x = tf.constant([
              [1,2],
              [4,5],
              [8,9]]
              )
print(x[0,:])
print(x[0:2,:])
print(x[1:3,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 5]
 [8 9]], shape=(2, 2), dtype=int32)


### Reshaping

In [19]:
x = tf.range(9)
print(x)
x = tf.reshape(x,shape=(3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [20]:
x = tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
